version: 2.1
jobs:
  build:
    working_directory: ~/quick-serve
    docker:
      - image: circleci/python:3.6.4
  steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
    - run:
        command: |
          sudo pip3 install -r dev-requirements.txt
    - run:
        - command |
          python3 -m unittest discover src/tests
    - store_test_results:
        path: test-results