version: 2.1
jobs:
  build:
    working_directory: ~/quick-serve
    docker:
      - image: circleci/python:3.6.4
  test:
    steps:
      - checkout
      - run: pip install -r dev-requirements.txt
      - run:
          - name: Run unittest
          - command |
            python -m unittest discover src/tests
      - store_test_results:
          path: test-results